ITEM_MAPPING = {
    -- Masks
    [63] = {"allnightmask","toggle"},
    [64] = {"blastmask","toggle"},
    [65] = {"bremenmask","toggle"},
    [66] = {"bunnyhood","toggle"},
    [67] = {"captainhat","toggle"},
    [68] = {"circusleadermask","toggle"},
    [69] = {"couplesmask","toggle"},
    [70] = {"dekumask","toggle"},
    [71] = {"dongeromask","toggle"},
    [72] = {"fiercedeitymask","toggle"},
    [73] = {"garomask","toggle"},
    [74] = {"giantmask","toggle"},
    [75] = {"gibdomask","toggle"},
    [76] = {"goronmask","toggle"},
    [77] = {"fairymask","toggle"},
    [78] = {"kafeimask","toggle"},
    [79] = {"kamaromask","toggle"},
    [80] = {"keatonmask","toggle"},
    [81] = {"postmanhat","toggle"},
    [82] = {"romanimask","toggle"},
    [83] = {"maskofscents","toggle"},
    [84] = {"stonemask","toggle"},
    [85] = {"maskoftruth","toggle"},
    [86] = {"zoramask","toggle"},

    -- Songs
    [112] = {"goronlullaby","progressive"},
    [139] = {"song_double_time","toggle"},
    [140] = {"elegy","toggle"},
    [141] = {"epona","toggle"},
    [142] = {"healing","toggle"},
    [143] = {"song_inverted_time","toggle"},
    [144] = {"goronlullaby","progressive"},
    [145] = {"goronlullaby","progressive"},
    [146] = {"newwave","toggle"},
    [147] = {"oathtoorder","toggle"},
    [148] = {"song_saria","toggle"},
    [149] = {"soaring","toggle"},
    [150] = {"sonata","toggle"},
    [151] = {"storms","toggle"},
    [152] = {"song_sun","toggle"},
    [153] = {"time","toggle"},
    -- Individually-named clock items (214-219) each light their own dedicated
    -- toggle -- these used to all collapse into the generic "clock_shuffle_time"
    -- progressive counter, which could never show WHICH specific half-day(s)
    -- were owned, only how many. "Progressive Time" (220) is the one genuinely
    -- progressive item (used in ascending/descending clock_shuffle modes,
    -- where order matters but identity doesn't) and keeps the counter widget.
    [214] = {"time_day1","toggle"},
    [215] = {"time_day2","toggle"},
    [216] = {"time_day3","toggle"},
    [217] = {"time_night1","toggle"},
    [218] = {"time_night2","toggle"},
    [219] = {"time_night3","toggle"},
    [220] = {"clock_shuffle_time","progressive"},

    -- Equipment (progressive)
    [9] = {"bombbag","progressive"},
    [10] = {"bombbag","progressive"},
    [11] = {"bombbag","progressive"},
    [23] = {"bow","progressive"},
    [36] = {"magic","progressive"},
    [110] = {"bombbag","progressive"},
    [111] = {"bow","progressive"},
    [113] = {"magic","progressive"},
    [114] = {"sword","progressive"},
    [115] = {"wallet","progressive"},
    [116] = {"bow","progressive"},
    [117] = {"bow","progressive"},
    [131] = {"shield","progressive"},
    [132] = {"shield","progressive"},
    [133] = {"magic","progressive"},
    [211] = {"sword","progressive"},
    [212] = {"sword","progressive"},
    [213] = {"sword","progressive"},
    [230] = {"wallet","progressive"},
    [231] = {"wallet","progressive"},
    [238] = {"wallet","progressive"},

    -- Equipment (misc)
    [15] = {"bombers_notebook","toggle"},
    [35] = {"double_defense","toggle"},
    [48] = {"fairysword","toggle"},
    [49] = {"spin_attack","toggle"},
    [53] = {"heart_container","consumable"},
    [54] = {"heart_piece","consumable"},
    [237] = {"skeleton_key","toggle"},

    -- Dungeon items (Woodfall / Snowhead / Great Bay / Stone Tower)
    [43] = {"bosskey_gb","toggle"},
    [44] = {"compass_greatbay","toggle"},
    [45] = {"map_greatbay_temple","toggle"},
    [46] = {"smallkey_gb","toggle"},
    [134] = {"bosskey_sh","toggle"},
    [135] = {"compass_snowhead","toggle"},
    [136] = {"map_snowhead_temple","toggle"},
    [137] = {"smallkey_sh","consumable"},
    [206] = {"bosskey_st","toggle"},
    [207] = {"compass_stonetower","toggle"},
    [208] = {"map_stonetower_temple","toggle"},
    [209] = {"smallkey_st","consumable"},
    [232] = {"bosskey_wf","toggle"},
    [233] = {"compass_woodfall","toggle"},
    [234] = {"map_woodfall_temple","toggle"},
    [235] = {"smallkey_wf","toggle"},

    -- Region (Tingle) maps
    [221] = {"map_clocktown","toggle"},
    [222] = {"map_greatbay","toggle"},
    [223] = {"map_romani","toggle"},
    [224] = {"map_snowhead","toggle"},
    [225] = {"map_stonetower","toggle"},
    [226] = {"map_woodfall","toggle"},

    -- Dungeon rewards / stray fairies / skulltulas
    [25] = {"fairy_ct","toggle"},
    [47] = {"fairy_gb","consumable"},
    [51] = {"skull_gb","consumable"},
    [52] = {"skull_ss","consumable"},
    [120] = {"gohtremains","toggle"},
    [121] = {"gyorgremains","toggle"},
    [122] = {"odolwaremains","toggle"},
    [123] = {"twinmoldremains","toggle"},
    [138] = {"fairy_sh","consumable"},
    [210] = {"fairy_st","consumable"},
    [236] = {"fairy_wf","consumable"},

    -- Items (misc)
    [1] = {"ability_swim","toggle"},
    [2] = {"firearrow","toggle"},
    [3] = {"icearrow","toggle"},
    [4] = {"lightarrow","toggle"},
    [18] = {"chateau","toggle"},
    [19] = {"empty_bottle","toggle"},
    [20] = {"gold_dust","toggle"},
    [21] = {"milk","toggle"},
    [22] = {"redpotion","toggle"},
    [26] = {"landdeed","toggle"},
    [27] = {"mountaindeed","toggle"},
    [28] = {"oceandeed","toggle"},
    [29] = {"swampdeed","toggle"},
    -- Deku Nut / Deku Stick: logic only cares about "have at least one" --
    -- has_item(ITEM_DEKU_NUT/STICK) is satisfied by any of the stack-size
    -- variants (see ITEM_TO_ITEMS in LogicHelpersGen.py) -- so only the base
    -- single-pickup id is wired to a widget; the "5x"/"10x" refill variants
    -- (ids 31, 32, 34) are deliberately left untracked, same as other junk
    -- refills, and still count via LOGIC_COUNTS if received over the network
    -- (see the NAME_TO_CODE fallback in archipelago.lua).
    [30] = {"dekunuts","toggle"},
    [33] = {"dekusticks","toggle"},
    [55] = {"hookshot","toggle"},
    [57] = {"lensoftruth","toggle"},
    [58] = {"kafeiletter","toggle"},
    [59] = {"mamaletter","toggle"},
    [60] = {"magicbeans","consumable"},
    [88] = {"moontear","toggle"},
    [96] = {"ocarina","toggle"},
    [107] = {"memoriespendant","toggle"},
    [108] = {"pictobox","toggle"},
    [109] = {"powderkeg","toggle"},
    [124] = {"roomkey","toggle"},

    -- Frogs
    [38] = {"frog_blue","toggle"},
    [39] = {"frog_cyan","toggle"},
    [40] = {"frog_pink","toggle"},
    [41] = {"frog_white","toggle"},

    -- Owl statues
    [97] = {"owl_clocktown","toggle"},
    [98] = {"owl_greatbaycoast","toggle"},
    [99] = {"owl_ikanacanyon","toggle"},
    [100] = {"owl_milkroad","toggle"},
    [101] = {"owl_mountainvillage","toggle"},
    [102] = {"owl_snowhead","toggle"},
    [103] = {"owl_southernswamp","toggle"},
    [104] = {"owl_stonetower","toggle"},
    [105] = {"owl_woodfall","toggle"},
    [106] = {"owl_zoracape","toggle"},

    -- Ocarina buttons
    [91] = {"ocarina_button_a","toggle"},
    [92] = {"ocarina_button_cdown","toggle"},
    [93] = {"ocarina_button_cright","toggle"},
    [94] = {"ocarina_button_cleft","toggle"},
    [95] = {"ocarina_button_cup","toggle"},

    -- Boss souls
    [154] = {"soul_boss_goht","toggle"},
    [155] = {"soul_boss_gyorg","toggle"},
    [156] = {"soul_boss_majora","toggle"},
    [157] = {"soul_boss_odolwa","toggle"},
    [158] = {"soul_boss_twinmold","toggle"},

    -- Enemy souls (bestiary)
    [159] = {"soul_alien","toggle"},
    [160] = {"soul_armos","toggle"},
    [161] = {"soul_bad_bat","toggle"},
    [162] = {"soul_beamos","toggle"},
    [163] = {"soul_boe","toggle"},
    [164] = {"soul_bubble","toggle"},
    [165] = {"soul_captain_keeta","toggle"},
    [166] = {"soul_chuchu","toggle"},
    [167] = {"soul_death_armos","toggle"},
    [168] = {"soul_deep_python","toggle"},
    [169] = {"soul_deku_baba","toggle"},
    [170] = {"soul_dexihand","toggle"},
    [171] = {"soul_dinolfos","toggle"},
    [172] = {"soul_dodongo","toggle"},
    [173] = {"soul_dragonfly","toggle"},
    [174] = {"soul_eeno","toggle"},
    [175] = {"soul_eyegore","toggle"},
    [176] = {"soul_freezard","toggle"},
    [177] = {"soul_garo","toggle"},
    [178] = {"soul_gekko","toggle"},
    [179] = {"soul_giant_bee","toggle"},
    [180] = {"soul_gomess","toggle"},
    [181] = {"soul_guay","toggle"},
    [182] = {"soul_hiploop","toggle"},
    [183] = {"soul_igos_du_ikana","toggle"},
    [184] = {"soul_iron_knuckle","toggle"},
    [185] = {"soul_keese","toggle"},
    [186] = {"soul_leever","toggle"},
    [187] = {"soul_like_like","toggle"},
    [188] = {"soul_mad_scrub","toggle"},
    [189] = {"soul_nejiron","toggle"},
    [190] = {"soul_octorok","toggle"},
    [191] = {"soul_peahat","toggle"},
    [192] = {"soul_pirate","toggle"},
    [193] = {"soul_poe","toggle"},
    [194] = {"soul_redead","toggle"},
    [195] = {"soul_shellblade","toggle"},
    [196] = {"soul_skullfish","toggle"},
    [197] = {"soul_skulltula","toggle"},
    [198] = {"soul_snapper","toggle"},
    [199] = {"soul_stalchild","toggle"},
    [200] = {"soul_takkuri","toggle"},
    [201] = {"soul_tektite","toggle"},
    [202] = {"soul_wallmaster","toggle"},
    [203] = {"soul_wart","toggle"},
    [204] = {"soul_wizrobe","toggle"},
    [205] = {"soul_wolfos","toggle"},

    -- Triforce
    [229] = {"triforce_piece","consumable"},
}
